### ISSUE TITLE
No C bindings for HighwayTreeHash and SipHash

### ISSUE THREAD

**Issue by vks** [google/highwayhash#11]
It used to be possible to bind against these, however this is no longer the case.

**Comment by jan-wassenberg** [comment]
Hi Vinzent, we were keen on simplifying the headers (already complicated due to conditional compilation  and *State classes). How about this approach using a separate header?

**Comment by vks** [comment]
I think that would be the best solution.

**Comment by jan-wassenberg** [comment]
Glad to hear it, thanks :)

**Comment by vks** [comment]
The bindings seem a bit inconsistent:

* `ScalarHighwayTreeHashC` and `SSE41HighwayTreeHashC` seem to duplicate `ScalarHighwayTreeHash` and `SSE41HighwayTreeHash`. I think only the ones with a C suffix should exist?
* There is `ScalarSipTreeHash` and `SipTreeHash`. They should probably get a `C` suffix as well?
* `HighwayTreeHashC` was not callable from C before, so it's nice to have it.
* There is no `SipHashC`.

I'll test the bindings once I get the build working again (#12).

**Comment by jan-wassenberg** [comment]
The C-suffix functions have two disadvantages: they're harder to inline (requires link-time inlining because they're not in the header) and the key parameter is not type-safe (can cause out of bounds accesses - SipHash expects 2 uint64, the others 4). That's why we'd like to keep the C bindings separate :)

Honestly, I don't see much value in SipTreeHash because it's not drop-in compatible with SipHash, nor is it as fast as HighwayHash. Still, we can add their bindings for completeness (plus SipHashC - thanks for pointing that out). Please feel free to re-open if needed :)

**Comment by vks** [comment]
I see. I bound against the non-suffix functions and it worked, probably due to an implicit cast.

Looks good to me, except that `SipHashC` seems to be missing from `c_bindings.h`.

**Comment by jan-wassenberg** [comment]
Thanks for looking, sorry about the missing SipHashC. Will add that next week :)

**Comment by jan-wassenberg** [comment]
Done :)

**Comment by vks** [comment]
Great, thanks!
