### ISSUE TITLE
A Cmple question: Why not in C also

### ISSUE THREAD

**Issue by Sanmayce** [google/highwayhash#15]
Hi,
I wish to run your **scalar_highway_tree_hash** using 64bit Intel Optimizer, two things:
- What are the drawbacks of having the C counterpart of your CC master?
- If you are not willing to write it in C, could you make a benchmark tool featuring simple main loop and hashing fixed length data - I want to test it by feeding it with 1 trillion Knight-Tours and compare the dispersion quality of:
- CRC32C1_8slice: 0x82F63B78 polynomial used
- CRC32C2_8slice: 0x8F6E37A0 polynomial used
- CRC32K1_8slice: 0xBA0DC66B polynomial used
- CRC32K2_8slice: 0x90022004 polynomial used
- FNV1A_YoshimitsuTRIAD

The console benchmarker, in C, is there:
http://www.linuxquestions.org/questions/programming-9/c-code-to-test-cpu-performances-benchmarking-4175581626/#post5570720

Since I am very fond of English language x-grams (2..114 bytes long phrases), 2-3 billion in use currently, I need hasher having collisions at each slot not exceeding some number, e.g. 10, as in the dump below:
`
FNV1A_YoshimitsuTRIAD: KT_derivatives = 00,000,067,108,865; 000,000,005 x MAXcollisionsAtSomeSlots = 000,011; HASHfreeSLOTS = 0,025,228,150; HashUtilization = 062%
`

`
CRC32K1_8slice       : KT_derivatives = 00,000,067,108,865; 000,000,001 x MAXcollisionsAtSomeSlots = 000,011; HASHfreeSLOTS = 0,024,687,907; HashUtilization = 063%
`

`
CRC32K2_8slice       : KT_derivatives = 00,000,067,108,865; 000,000,005 x MAXcollisionsAtSomeSlots = 000,010; HASHfreeSLOTS = 0,024,680,327; HashUtilization = 063%
`

`
CRC32C1_8slice       : KT_derivatives = 00,000,067,108,865; 000,000,002 x MAXcollisionsAtSomeSlots = 000,011; HASHfreeSLOTS = 0,024,689,921; HashUtilization = 063%
`

`
CRC32C2_8slice       : KT_derivatives = 00,000,067,108,865; 000,000,006 x MAXcollisionsAtSomeSlots = 000,010; HASHfreeSLOTS = 0,024,688,174; HashUtilization = 063%
`

**Comment by jan-wassenberg** [comment]
Hi, not sure I understand what you're asking.
Does your CPU support SSE4.1? If so, SSE41HighwayTreeHash is much faster than ScalarHighwayTreeHash.

It would be quite hard (and disadvantageous) to switch the entire implementation to C, but what you can do is compile with a C++ compiler and link it with a C program.
The wrappers in c_bindings.h are not used in the C++ interface because those are not type-safe (it is possible to pass 2 keys to a function expecting 4, or vice versa) and harder to inline (your compiler would need to support whole-program analysis).

**Comment by Sanmayce** [comment]
Thanks, forget it.
My wish was to hash 128 bytes long blocks and see what dispersion/speed **scalar_highway_tree_hash** written in C would offer.

**Comment by jan-wassenberg** [comment]
OK :)
