### ISSUE TITLE
Can we let runtime dispatcher support HighwayHashCatT's Append and Finalize operation?

### ISSUE THREAD

**Issue by wanghan02** [google/highwayhash#65]
The runtime dispatcher InstructionSets::Run can only do the hash calculation once. If we want to append another block of data later and do the Finalize at the end (what HighwayHashCatT is used for), it doesn't work. This is because we need the hash state variable stored for Append and Finalize operations. But we cannot store this hash state variable directly in the application (outside the target TU). This means the portable version is the only choice for developers who want to use Append and Finalize (normally we cannot guarantee the user's CPU supports SSE4.1 or AVX2). The portable version is slow and makes highwayhash less attractive. 

However, can we provide a solution to this? Say provide a hash state variable as a block of memory. And all the calculations are done in the target TU with reinterpret_cast to HHStatePortable/SSE41/AVX2.

**Comment by jan-wassenberg** [comment]
This is an interesting question, thanks for bringing it up. CPU dispatch in every Append could work, but that's an extra ~4 cycles plus the state will have to be loaded/stored rather than residing in registers.
Would it be an option for the caller of Append to instead be written as CPU-specific code with this template mechanism? Then the `::Run` would only need to be called once for the entire series of Append.
If that's not an option, I would be open to an opaque block of memory solution as you suggest.
